name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Download latest list of projects
        run: curl -o projects.json https://meaningfulcode.org/api/projects

      - name: Convert to README.md
        run: python project.py --to-readme --ref-readme README.md projects.json > README.md

      - name: Check for README.md changes
        id: check_changes
        run: |
          git diff --exit-code README.md || echo "::set-output name=changed::true"

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'meaningfulcode-github-actions[bot]'
          git config --global user.email 'meaningfulcode-github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "README.md: update project list from meaningfulcode.org"
          git push origin HEAD:readme-update-projects

      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "README.md: update project list from meaningfulcode.org",
              head: "readme-update-projects",
              base: "main",
              body: "This automated update was pulled from https://meaningfulcode.org/api/projects"
            })
